### ISSUE TITLE
NAN outputs resulting in a blank video

### ISSUE THREAD

**Issue by rakesh-reddy95** [omerbt/TokenFlow#14]
@omerbt  I have run tokenflow using pnp but the results are blank and the decoded latents are NaN. While the inversion during the preprocess happened correctly.

**Comment by pansanity666** [comment]
Same here. Any idea about it?

**Comment by rakesh-reddy95** [comment]
Which version of SD are you using?

**Comment by pansanity666** [comment]
> Which version of SD are you using?

I was using SD1.5.
I find that several frames get NAN outputs after DDIM Inversion and reconstruction, therefore leads to the following NAN outputs in editing stage.
Not sure the reason for it.

**Comment by rakesh-reddy95** [comment]
I started using SD 2.1 base version which didn't produce NaN in DDIM inversion and reconstruction. Also, you can try calculating the next step velocity along with the previous step velocity which was removing NaN.
