### ISSUE TITLE
Default data path in config_sdedit.yaml is to a missing file

### ISSUE THREAD

**Issue by cysmith** [omerbt/TokenFlow#23]
In file `config_sdedit.yaml`, this:
`data_path:  'wolf-part'`
should be:
`data_path:  'data/woman-running'`

And the prompt should be updated from:
`a shiny silver robotic wolf`
to:
`"a marble sculpture of a woman running, Venus de Milo"`

**Comment by argentinox** [comment]
Sorry, but the correct way to fix that "problem" is this:

In file config_sdedit.yaml, this:
data_path:  'wolf-part'
should be:
data_path:  'data/wolf'
